### ISSUE TITLE
Trying this library on stable and futures 0.1?

### ISSUE THREAD

**Issue by apiraino** [vavrusa/memcache-async#3]
Hello,

I wanted to try this library on the following setup:
- Rust stable (1.36 as of yet)
- futures 0.1.28
- tokio 0.1.22

I see a recent PR from @xofyarg moves this library to futures 0.3 and I'm a bit confused on how to use this library. Can I still use it from such setup?

Also, this library does not take care of the connection to memcached, right? 

Looking at the [few examples](https://github.com/vavrusa/memcache-async/blob/7ed04c729de2ebe59fdf6d7562b718584246626e/src/ascii.rs#L129) I dont have clear if I can use it through simple Futures.

A bit more info and examples would be greatly appreciated.

**Comment by vavrusa** [comment]
Hi 👋 this library is targeting the std::Future primarily (tokio is in the process of converting too), but you should be able to use it with any AsyncRead + AsyncWrite future through [compat](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.16/futures/compat/index.html). I made you an example here: https://github.com/vavrusa/memcache-async/blob/master/examples/tcp-compat.rs

It will be difficult to use without async however as the protocol borrows mutably on get/set and in order to do that you'll need pinning.

**Comment by apiraino** [comment]
Thank you! :+1:
